In [1]:
import pandas as pd

# Path to CSV
csv_file = "../data/NIFTY 50_Historical_PR_01011990to11102024.csv"

# Load dataset into pandas DataFrame
df = pd.read_csv(csv_file)

# Suggestion applied: Rename columns for clarity
df.rename(columns={'Close':'Closing_Price', 'Volume':'Trade_Volume'}, inplace=True)

# Preview first 5 rows
df.head()

  Index Name        Date      Open      High       Low  Closing_Price
0   NIFTY 50  11-10-2024   24985.3  25028.65  24920.05       24964.25
1   NIFTY 50  10-10-2024  25067.05  25134.05   24979.4       24998.45
2   NIFTY 50  09-10-2024   25065.8  25234.05   24947.7       24981.95
3   NIFTY 50  08-10-2024   24832.2     25044   24756.8       25013.15
4   NIFTY 50  07-10-2024   25084.1     25143  24694.35       24795.75

In [2]:
import pandas as pd

# Path to your CSV file
csv_file = "../data/NIFTY 50_Historical_PR_01011990to11102024.csv"

# Load dataset into pandas DataFrame
df = pd.read_csv(csv_file)

# Rename columns for clarity
df.rename(columns={'Close':'Closing_Price', 'Volume':'Trade_Volume'}, inplace=True)

# Convert 'Date' column to datetime (dayfirst=True since format is DD/MM/YYYY)
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# Sort data by Date ascending (oldest → newest)
df.sort_values('Date', inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

# Preview first 5 rows
df.head()

  Index Name       Date Open High Low  Closing_Price
0   NIFTY 50 1990-07-03    -    -   -         279.02
1   NIFTY 50 1990-07-05    -    -   -         284.04
2   NIFTY 50 1990-07-06    -    -   -         289.04
3   NIFTY 50 1990-07-09    -    -   -         289.69
4   NIFTY 50 1990-07-10    -    -   -         288.69

In [3]:
# Keep data from 2000 onwards
df = df[df['Date'] >= '2000-01-01']
df.reset_index(drop=True, inplace=True)

# Preview
df.head()

  Index Name       Date     Open     High      Low  Closing_Price
0   NIFTY 50 2000-01-03  1482.15   1592.9  1482.15         1592.2
1   NIFTY 50 2000-01-04   1594.4  1641.95   1594.4         1638.7
2   NIFTY 50 2000-01-05  1634.55   1635.5  1555.05         1595.8
3   NIFTY 50 2000-01-06   1595.8     1639   1595.8         1617.6
4   NIFTY 50 2000-01-07   1616.6  1628.25   1597.2         1613.3

In [4]:
# Check for missing values
print(df.isnull().sum())

# Fill missing values using previous day
df.ffill(inplace=True)  # forward-fill missing values

Index Name       0
Date             0
Open             0
High             0
Low              0
Closing_Price    0
dtype: int64

In [5]:
# Filter data from year 2000 onwards

df = df[df['Date'].dt.year >= 2000]

# Reset index after filtering
df.reset_index(drop=True, inplace=True)

# Check first and last dates
print("First Date:", df['Date'].min())
print("Last Date:", df['Date'].max())

# Check number of rows
print("Total Rows After Filtering:", len(df))

# Preview data
df.head()

First Date: 2000-01-03 00:00:00
Last Date: 2024-10-11 00:00:00
Total Rows After Filtering: 6163

  Index Name       Date     Open     High      Low  Closing_Price
0   NIFTY 50 2000-01-03  1482.15   1592.9  1482.15         1592.2
1   NIFTY 50 2000-01-04   1594.4  1641.95   1594.4         1638.7
2   NIFTY 50 2000-01-05  1634.55   1635.5  1555.05         1595.8
3   NIFTY 50 2000-01-06   1595.8     1639   1595.8         1617.6
4   NIFTY 50 2000-01-07   1616.6  1628.25   1597.2         1613.3

In [6]:
# Create 50-day Moving Average
df['MA_50'] = df['Closing_Price'].rolling(window=50).mean()

# Create 200-day Moving Average
df['MA_200'] = df['Closing_Price'].rolling(window=200).mean()

# Create Daily Return
df['Daily_Return'] = df['Closing_Price'].pct_change()

# Create Trend column (1 = Up, 0 = Down)
df['Trend'] = (df['Closing_Price'] > df['Closing_Price'].shift(1)).astype(int)

# Check new columns
df.head(10)

,Index Name,Date,Open,High,Low,Closing_Price,MA_50,MA_200,Daily_Return,Trend
0,NIFTY 50,2000-01-03,1482.15,1592.9,1482.15,1592.20,NaN,NaN,NaN,0
1,NIFTY 50,2000-01-04,1594.4,1641.95,1594.4,1638.70,NaN,NaN,0.029205,1
2,NIFTY 50,2000-01-05,1634.55,1635.5,1555.05,1595.80,NaN,NaN,-0.026179,0
3,NIFTY 50,2000-01-06,1595.8,1639,1595.8,1617.60,NaN,NaN,0.013661,1
4,NIFTY 50,2000-01-07,1616.6,1628.25,1597.2,1613.30,NaN,NaN,-0.002658,0
5,NIFTY 50,2000-01-10,1615.65,1662.1,1614.95,1632.95,NaN,NaN,0.012180,1
6,NIFTY 50,2000-01-11,1633.25,1639.9,1548.25,1572.50,NaN,NaN,-0.037019,0
7,NIFTY 50,2000-01-12,1572.3,1631.55,1571.7,1624.80,NaN,NaN,0.033259,1
8,NIFTY 50,2000-01-13,1627.85,1671.15,1613.65,1621.40,NaN,NaN,-0.002093,0
9,NIFTY 50,2000-01-14,1622.15,1627.4,1591.4,1622.75,NaN,NaN,0.000833,1

In [7]:
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.head()

,Index Name,Date,Open,High,Low,Closing_Price,MA_50,MA_200,Daily_Return,Trend
0,NIFTY 50,2000-10-19,1135.65,1171.5,1108.2,1166.15,1328.263,1459.62625,0.026540,1
1,NIFTY 50,2000-10-20,1166.2,1202.7,1166.2,1172.00,1324.791,1457.52525,0.005017,1
2,NIFTY 50,2000-10-23,1171.75,1172.15,1141.45,1143.95,1320.771,1455.05150,-0.023933,0
3,NIFTY 50,2000-10-24,1143,1155.35,1132.9,1152.45,1317.260,1452.83475,0.007430,1
4,NIFTY 50,2000-10-25,1158.2,1190.4,1157.25,1183.90,1314.723,1450.66625,0.027290,1

In [8]:
# Check total rows
total_rows = len(df)
print("Total Rows:", total_rows)

# Define training size (80%)
train_size = int(total_rows * 0.8)

# Split dataset
train_data = df[:train_size]
test_data = df[train_size:]

print("Training Data Size:", len(train_data))
print("Testing Data Size:", len(test_data))

# Check last date of training and first date of testing
print("Last Training Date:", train_data['Date'].iloc[-1])
print("First Testing Date:", test_data['Date'].iloc[0])

Total Rows: 5964
Training Data Size: 4771
Testing Data Size: 1193
Last Training Date: 2019-12-24 00:00:00
First Testing Date: 2019-12-26 00:00:00

In [9]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Select only Closing Price for LSTM
train_close = train_data[['Closing_Price']]
test_close = test_data[['Closing_Price']]

# Create scaler object
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit scaler only on training data
train_scaled = scaler.fit_transform(train_close)

# Transform testing data
test_scaled = scaler.transform(test_close)

print("Training Scaled Shape:", train_scaled.shape)
print("Testing Scaled Shape:", test_scaled.shape)

Training Scaled Shape: (4771, 1)
Testing Scaled Shape: (1193, 1)

In [11]:
# Function to create sequences

def create_sequences(data, time_steps=60):
    X = []
    y = []
    
    for i in range(time_steps, len(data)):
        X.append(data[i-time_steps:i, 0])  # last 60 days
        y.append(data[i, 0])              # next day
        
    return np.array(X), np.array(y)

In [12]:
# Create sequences for training data
X_train, y_train = create_sequences(train_scaled, 60)

# Create sequences for testing data
X_test, y_test = create_sequences(test_scaled, 60)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (4711, 60)
y_train shape: (4711,)
X_test shape: (1133, 60)
y_test shape: (1133,)

In [13]:
# Reshape for LSTM (3D input)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

print("Reshaped X_train:", X_train.shape)
print("Reshaped X_test:", X_test.shape)

Reshaped X_train: (4711, 60, 1)
Reshaped X_test: (1133, 60, 1)

In [14]:
import numpy as np

np.save("X_train.npy", X_train)
np.save("y_train.npy", y_train)
np.save("X_test.npy", X_test)
np.save("y_test.npy", y_test)

print("Files saved successfully")

Files saved successfully

In [17]:
np.save("X_train.npy", X_train)
X_train = np.load("X_train.npy")